### ISSUE TITLE
Not working due to unsupported ruby version by Heroku 

### ISSUE THREAD

**Issue by Bnaya** [choonkeat/heroku-log-s3#1]
Heroku changed they minimum supported ruby versions
https://devcenter.heroku.com/articles/ruby-support#supported-runtimes

**Comment by mcnelson** [comment]
I just opened a PR to bump the ruby version- https://github.com/choonkeat/heroku-log-s3/pull/2

**Comment by choonkeat** [comment]
Should be fixed in #2
